const Homeproduct= 
[
    {
        id:1,
        Name:"LG 26' TV",
        price: "26",
        image:"image/p1.webp", 
        cat:"tv",
        type: "new",
    },
    {
        id:2,
        Name:"Macbook pro",
        price: "26",
        image:"image/p2.webp",
        cat:"laptop",
        type: "top",
    },
    {
        id:3,
        Name:"Apple watch series 6",
        price: "26",
        image:"image/p3.webp",
        cat:"watch",
        type: "featured",
    },
    {
        id:4,
        Name:"Apple watch series 6",
        price: "626",
        image:"image/p9.jpg",
        cat:"laptop",
        type: "new",
    },
    {
        id:5,
        Name:"Alexa",
        price: "26",
        image:"image/p4.webp",
        cat:"speaker",
        type: "top",
    },
    {
        id:6,
        Name:"CCTV camera",
        price: "26",
        image:"image/p5.webp",
        cat:"electronics",
        type: "new",
    },
    {
        id:7,
        Name:"CCTV camera",
        price: "26",
        image:"image/p10.jpg",
        cat:"headphones",
        type: "featured",
    },
    {
        id:8,
        Name:"CCTV camera",
        price: "26",
        image:"image/p11.jpg",
        cat:"electronics",
        type: "top",
    },
    {
        id:9,
        Name:"product6",
        price: "26",
        image:"image/p6.webp",
        cat:"",
        type: "featured",
    },
    {
        id:10,
        Name:"product7",
        price: "26",
        image:"image/p7.webp",
        cat:"speaker",
        type: "top",
    },
    {
        id:11,
        Name:"product7",
        price: "26",
        image:"image/p8.webp",
        cat:"speaker",
        type: "top",
    },
    {
        id:12,
        Name:"product7",
        price: "26",
        image:"image/p12.jpg",
        cat:"speaker",
        type: "new",
    },/*
    {
        id:9,
        Name:"product7",
        price: "26",
        image:"image/p9.webp",
        cat:"",
        type: "new",
    },
    {
        id:10,
        Name:"product7",
        price: "26",
        image:"image/p10.webp",
        cat:"",
        type: "new",
    },
    {
        id:11,
        Name:"product7",
        price: "26",
        image:"image/p11.webp",
        cat:"",
        type: "new",
    },
    {
        id:12,
        Name:"product7",
        price: "26",
        image:"image/p12.webp",
        cat:"",
        type: "new",
    }, */
]

export default Homeproduct;