const Homeproduct= 
[
    {
        id:1,
        Name:"LG 26' TV",
        price: "1299",
        image:"image/p1.webp", 
        cat:"tv",
        type: "new",
    },
    {
        id:2,
        Name:"Macbook pro",
        price: "1499",
        image:"image/p2.webp",
        cat:"laptop",
        type: "top",
    },
    {
        id:3,
        Name:"Apple watch 6",
        price: "899",
        image:"image/p3.webp",
        cat:"watch",
        type: "featured",
    },
    {
        id:4,
        Name:"Microsoft Surface ",
        price: "1099",
        image:"image/p9.jpg",
        cat:"laptop",
        type: "new",
    },
    {
        id:5,
        Name:"Alexa",
        price: "249",
        image:"image/p4.webp",
        cat:"speaker",
        type: "top",
    },
    {
        id:6,
        Name:"Beats by Dre",
        price: "549",
        image:"image/beats.jpeg",
        cat:"headphones",
        type: "new",
    },
    {
        id:7,
        Name:"Beats speaker",
        price: "729",
        image:"image/beatsSpeaker.jpg",
        cat:"speaker",
        type: "featured",
    },
    {
        id:8,
        Name:"Apple Imac",
        price: "2499",
        image:"image/imac.jpeg",
        cat:"laptop",
        type: "top",
    },
    {
        id:9,
        Name:"Motorola g45 5G",
        price: "399",
        image:"image/p6.webp",
        cat:"phone",
        type: "featured",
    },
    {
        id:10,
        Name:"Marshall speakers",
        price: "449",
        image:"image/marshall.webp",
        cat:"speaker",
        type: "top",
    },
    {
        id:11,
        Name:"Alexa",
        price: "199",
        image:"image/p8.webp",
        cat:"speaker",
        type: "top",
    },
    {
        id:12,
        Name:"Iphone SE",
        price: "1399",
        image:"image/iphonenew.webp",
        cat:"phone",
        type: "new",
    },/*
    {
        id:9,
        Name:"product7",
        price: "26",
        image:"image/p9.webp",
        cat:"",
        type: "new",
    },
    {
        id:10,
        Name:"product7",
        price: "26",
        image:"image/p10.webp",
        cat:"",
        type: "new",
    },
    {
        id:11,
        Name:"product7",
        price: "26",
        image:"image/p11.webp",
        cat:"",
        type: "new",
    },
    {
        id:12,
        Name:"product7",
        price: "26",
        image:"image/p12.webp",
        cat:"",
        type: "new",
    }, */
]

export default Homeproduct;